[project]
name = 'Blockchain-Based-Financial-Stress-Testing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-collection]
path = 'contracts/data-collection.clar'
clarity_version = 2
epoch = 2.5

[contracts.institution-verification]
path = 'contracts/institution-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.regulatory-reporting]
path = 'contracts/regulatory-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-calculation]
path = 'contracts/risk-calculation.clar'
clarity_version = 2
epoch = 2.5

[contracts.scenario-definition]
path = 'contracts/scenario-definition.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
